CREATE TABLE APP_USER (
ID VARCHAR(255) PRIMARY KEY,
USERNAME VARCHAR(30) UNIQUE,
PASSWORD VARCHAR(255),
EMAIL VARCHAR(255) UNIQUE
);

CREATE TABLE USER_GROUP (
ID VARCHAR(255) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL
);

CREATE TABLE ITEM (
ID VARCHAR(255) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL
);

CREATE TABLE SHOPPING_LIST (
ID VARCHAR(255) PRIMARY KEY,
GROUP_ID VARCHAR(255) FOREIGN KEY REFERENCES GROUP(ID),
NAME VARCHAR(255) NOT NULL
);

CREATE TABLE GROUP_MEMBER (
USER_ID VARCHAR(255) NOT NULL,
GROUP_ID VARCHAR(255) NOT NULL
);

CREATE TABLE LIST_ITEM (
LIST_ID VARCHAR(255) NOT NULL,
ITEM_ID VARCHAR(255) NOT NULL,
QUANTITY INT,
PRIMARY KEY(LIST_ID, ITEM_ID)
);

